export const mockCases = [
  {
    id: "CYB-2025-001",
    title: "Online Banking Fraud",
    description: "Unauthorized access to online banking account resulting in fraudulent transactions totaling ₱50,000",
    priority: "high",
    status: "Under Investigation",
    officer: "Maria Santos",
    unit: "Economic Offenses Wing",
    date: "2025-01-20",
    riskScore: 85,
    evidence: 3,
    crimeType: "Online Banking Fraud",
    complainant: "Juan Dela Cruz",
    estimatedLoss: 50000,
    // Database schema fields
    userId: "user_123456789",
    fullName: "Juan Dela Cruz",
    email: "juan.delacruz@email.com",
    phoneNumber: "+63 917 123 4567",
    incidentDateTime: "2025-01-19T14:30:00+08:00",
    incidentLocation: "BPI Branch, Makati City",
    complaintNumber: "CYB-2025-001",
    assignedOfficer: "Maria Santos",
    remarks: "Case assigned to Economic Offenses Wing for financial fraud investigation",
    createdAt: "2025-01-20T09:15:00+08:00",
    updatedAt: "2025-01-20T16:45:00+08:00",
    evidenceFiles: [
      {
        id: "ev_001",
        fileName: "banking_screenshot.png",
        fileType: "image/png",
        fileSize: 2048576,
        uploadedAt: "2025-01-20T09:20:00+08:00"
      },
      {
        id: "ev_002",
        fileName: "transaction_receipt.pdf",
        fileType: "application/pdf",
        fileSize: 1024000,
        uploadedAt: "2025-01-20T09:22:00+08:00"
      },
      {
        id: "ev_003",
        fileName: "email_notification.png",
        fileType: "image/png",
        fileSize: 856432,
        uploadedAt: "2025-01-20T09:25:00+08:00"
      }
    ]
  },
  {
    id: "CYB-2025-002",
    title: "Social Media Harassment",
    description: "Continuous harassment and threats received through social media platforms over the past month",
    priority: "medium",
    status: "Pending",
    officer: "Diana Lopez",
    unit: "Cyber Crime Against Women and Children",
    date: "2025-01-19",
    riskScore: 65,
    evidence: 5,
    crimeType: "Online Harassment",
    complainant: "Maria Santos",
    estimatedLoss: 0,
    // Database schema fields
    userId: "user_987654321",
    fullName: "Maria Santos",
    email: "maria.santos@email.com",
    phoneNumber: "+63 916 987 6543",
    incidentDateTime: "2025-01-18T20:15:00+08:00",
    incidentLocation: "Online - Social Media Platforms",
    complaintNumber: "CYB-2025-002",
    assignedOfficer: "Diana Lopez",
    remarks: "Case assigned to Cyber Crime Against Women and Children unit",
    createdAt: "2025-01-19T08:30:00+08:00",
    updatedAt: "2025-01-19T08:30:00+08:00",
    evidenceFiles: [
      {
        id: "ev_004",
        fileName: "facebook_threats.png",
        fileType: "image/png",
        fileSize: 1234567,
        uploadedAt: "2025-01-19T08:35:00+08:00"
      },
      {
        id: "ev_005",
        fileName: "instagram_messages.png",
        fileType: "image/png",
        fileSize: 987654,
        uploadedAt: "2025-01-19T08:37:00+08:00"
      },
      {
        id: "ev_006",
        fileName: "twitter_screenshots.png",
        fileType: "image/png",
        fileSize: 1567890,
        uploadedAt: "2025-01-19T08:40:00+08:00"
      },
      {
        id: "ev_007",
        fileName: "messenger_conversation.pdf",
        fileType: "application/pdf",
        fileSize: 2100000,
        uploadedAt: "2025-01-19T08:42:00+08:00"
      },
      {
        id: "ev_008",
        fileName: "profile_screenshots.png",
        fileType: "image/png",
        fileSize: 789456,
        uploadedAt: "2025-01-19T08:45:00+08:00"
      }
    ]
  },
  {
    id: "CYB-2025-003",
    title: "Phishing Email Campaign",
    description: "Large-scale phishing campaign targeting bank customers with fake login pages",
    priority: "high",
    status: "Requires More Info",
    officer: "Carlos Mendoza",
    unit: "Cyber Crime Investigation Cell",
    date: "2025-01-18",
    riskScore: 92,
    evidence: 2,
    crimeType: "Phishing",
    complainant: "BPI Bank",
    estimatedLoss: 250000,
    // Database schema fields
    userId: "user_bpi_security",
    fullName: "BPI Security Team",
    email: "security@bpi.com.ph",
    phoneNumber: "+63 2 8840 4000",
    incidentDateTime: "2025-01-17T10:00:00+08:00",
    incidentLocation: "Online - Email and Website",
    complaintNumber: "CYB-2025-003",
    assignedOfficer: "Carlos Mendoza",
    remarks: "Requires additional server logs and affected customer list",
    createdAt: "2025-01-18T14:20:00+08:00",
    updatedAt: "2025-01-18T18:30:00+08:00",
    evidenceFiles: [
      {
        id: "ev_009",
        fileName: "phishing_email_sample.eml",
        fileType: "message/rfc822",
        fileSize: 45632,
        uploadedAt: "2025-01-18T14:25:00+08:00"
      },
      {
        id: "ev_010",
        fileName: "fake_website_screenshot.png",
        fileType: "image/png",
        fileSize: 3456789,
        uploadedAt: "2025-01-18T14:28:00+08:00"
      }
    ]
  },
  {
    id: "CYB-2025-004",
    title: "Identity Theft",
    description: "Personal information stolen and used to open fraudulent credit accounts",
    priority: "medium",
    status: "Under Investigation",
    officer: "Carlos Mendoza",
    unit: "Cyber Security Division",
    date: "2025-01-17",
    riskScore: 73,
    evidence: 4,
    crimeType: "Identity Theft",
    complainant: "Ana Reyes",
    estimatedLoss: 75000,
  },
  {
    id: "CYB-2025-005",
    title: "Ransomware Attack",
    description: "Company systems encrypted by ransomware with demand for ₱500,000 payment",
    priority: "high",
    status: "Resolved",
    officer: "Roberto Cruz",
    unit: "Cyber Crime Technical Unit",
    date: "2025-01-16",
    riskScore: 95,
    evidence: 7,
    crimeType: "Ransomware",
    complainant: "TechCorp Philippines",
    estimatedLoss: 500000,
  },
  {
    id: "CYB-2025-006",
    title: "Credit Card Fraud",
    description: "Unauthorized credit card transactions detected in multiple online purchases",
    priority: "medium",
    status: "Under Investigation",
    officer: "John Rodriguez",
    unit: "Economic Offenses Wing",
    date: "2025-01-15",
    riskScore: 68,
    evidence: 3,
    crimeType: "Credit Card Fraud",
    complainant: "Pedro Garcia",
    estimatedLoss: 25000,
  },
  {
    id: "CYB-2025-007",
    title: "Cyberbullying Case",
    description: "Student experiencing cyberbullying through various social media platforms and messaging apps",
    priority: "low",
    status: "Pending",
    officer: "Diana Lopez",
    unit: "Cyber Crime Against Women and Children",
    date: "2025-01-14",
    riskScore: 45,
    evidence: 2,
    crimeType: "Cyberbullying",
    complainant: "Rosa Mendoza",
    estimatedLoss: 0,
  },
  {
    id: "CYB-2025-008",
    title: "Data Breach Investigation",
    description: "Personal data of 10,000 customers leaked from company database",
    priority: "high",
    status: "Under Investigation",
    officer: "Carlos Mendoza",
    unit: "Cyber Security Division",
    date: "2025-01-13",
    riskScore: 88,
    evidence: 6,
    crimeType: "Data Breach",
    complainant: "DataSecure Inc",
    estimatedLoss: 100000,
  },
  {
    id: "CYB-2025-009",
    title: "Sextortion Case",
    description: "Victim being blackmailed with intimate images shared through social media",
    priority: "high",
    status: "Requires More Info",
    officer: "Diana Lopez",
    unit: "Cyber Crime Against Women and Children",
    date: "2025-01-12",
    riskScore: 90,
    evidence: 3,
    crimeType: "Sextortion",
    complainant: "Confidential",
    estimatedLoss: 0,
  },
  {
    id: "CYB-2025-010",
    title: "Government System Hacking",
    description: "Unauthorized access attempt detected on local government database system",
    priority: "high",
    status: "Under Investigation",
    officer: "Sofia Reyes",
    unit: "National Security Cyber Division",
    date: "2025-01-11",
    riskScore: 95,
    evidence: 4,
    crimeType: "Government System Hacking",
    complainant: "City Government of Manila",
    estimatedLoss: 0,
  },
]

