// PNP Units Mock Data with Crime Types
export const mockPNPUnits = [
  {
    id: "unit_001",
    unitName: "Cyber Crime Investigation Cell",
    unitCode: "PCU-001",
    category: "Communication & Social Media Crimes",
    description: "Handles phishing, social engineering, and communication-related cybercrimes",
    region: "National Capital Region (NCR)",
    maxOfficers: 20,
    currentOfficers: 15,
    activeCases: 34,
    resolvedCases: 128,
    successRate: 87.5,
    status: "active",
    crimeTypes: [
      "Phishing",
      "Social Engineering", 
      "Spam Messages",
      "Fake Social Media Profiles",
      "Online Impersonation",
      "Business Email Compromise",
      "SMS Fraud"
    ]
  },
  {
    id: "unit_002", 
    unitName: "Economic Offenses Wing",
    unitCode: "PCU-002",
    category: "Financial & Economic Crimes",
    description: "Investigates online banking fraud, investment scams, and financial crimes",
    region: "National Capital Region (NCR)",
    maxOfficers: 25,
    currentOfficers: 22,
    activeCases: 45,
    resolvedCases: 156,
    successRate: 82.3,
    status: "active",
    crimeTypes: [
      "Online Banking Fraud",
      "Credit Card Fraud", 
      "Investment Scams",
      "Cryptocurrency Fraud",
      "Online Shopping Scams",
      "Payment Gateway Fraud",
      "Insurance Fraud",
      "Tax Fraud",
      "Money Laundering"
    ]
  },
  {
    id: "unit_003",
    unitName: "Cyber Crime Against Women and Children", 
    unitCode: "PCU-005",
    category: "Harassment & Exploitation",
    description: "Investigates cyberstalking, online harassment, and exploitation",
    region: "National Capital Region (NCR)",
    maxOfficers: 22,
    currentOfficers: 18,
    activeCases: 28,
    resolvedCases: 89,
    successRate: 91.2,
    status: "active",
    crimeTypes: [
      "Cyberstalking",
      "Online Harassment",
      "Cyberbullying", 
      "Revenge Porn",
      "Sextortion",
      "Online Predatory Behavior",
      "Doxxing",
      "Hate Speech"
    ]
  }
];

// Mock PNP Officer Data
export const mockOfficerProfile = {
  id: "officer_001",
  firebase_uid: "firebase_officer_001",
  email: "j.smith@pnp.gov.ph",
  full_name: "John Reynaldo Smith",
  phone_number: "+63 912 345 6789",
  badge_number: "PNP-12345",
  rank: "Police Officer III",
  unit_id: "unit_001",
  unit: mockPNPUnits[0], // Cyber Crime Investigation Cell
  region: "National Capital Region (NCR)",
  status: "active",
  // Performance metrics
  total_cases: 156,
  active_cases: 12,
  resolved_cases: 134,
  success_rate: 86,
  avg_resolution_time: 4.2,
  // Additional profile info
  join_date: "2020-03-15",
  years_of_service: 5,
  specializations: ["Phishing Investigation", "Social Engineering", "Digital Forensics"],
  certifications: [
    {
      name: "Certified Cyber Crime Investigator",
      issuer: "PNP Cybercrime Division",
      valid_until: "2025-12-31",
      status: "active"
    },
    {
      name: "Digital Evidence Specialist", 
      issuer: "International Association of Computer Investigative Specialists",
      valid_until: "2025-06-30",
      status: "active"
    }
  ],
  upcoming_training: [
    {
      name: "Advanced Malware Analysis",
      scheduled_date: "2025-02-15",
      status: "enrolled"
    },
    {
      name: "Cryptocurrency Investigation",
      scheduled_date: "2025-03-10", 
      status: "pending"
    }
  ],
  profile_picture_url: null,
  bio: "Experienced cybercrime investigator specializing in phishing and social engineering cases. 5+ years with PNP Cybercrime Division.",
  last_login: "2025-01-30T08:15:00+08:00",
  login_count: 847,
  created_at: "2020-03-15T09:00:00+08:00",
  updated_at: "2025-01-30T08:15:00+08:00"
};

export const mockCases = [
  {
    id: "CYB-2025-001",
    title: "Online Banking Fraud",
    description: "Unauthorized access to online banking account resulting in fraudulent transactions totaling ₱50,000",
    priority: "high",
    status: "Under Investigation",
    officer: "Maria Santos",
    unit: "Economic Offenses Wing",
    date: "2025-01-20",
    riskScore: 85,
    evidence: 3,
    crime_type: "Online Banking Fraud",
    complainant: "Juan Dela Cruz",
    estimated_loss: 50000,
    // Database schema fields
    user_id: "user_123456789",
    full_name: "Juan Dela Cruz",
    email: "juan.delacruz@email.com",
    phone_number: "+63 917 123 4567",
    incident_date_time: "2025-01-19T14:30:00+08:00",
    incident_location: "BPI Branch, Makati City",
    complaint_number: "CYB-2025-001",
    assigned_officer: "Maria Santos",
    assigned_officer_id: "officer_002",
    assigned_unit: "Economic Offenses Wing",
    unit_id: "unit_002",
    // Dynamic fields (category-specific)
    platform_website: "BPI Online",
    account_reference: "ACC-789012345",
    // AI Enhancement fields
    ai_priority: "high",
    ai_risk_score: 88,
    ai_confidence_score: 92,
    last_ai_assessment: "2025-01-20T09:30:00+08:00",
    remarks: "Case assigned to Economic Offenses Wing for financial fraud investigation",
    created_at: "2025-01-20T09:15:00+08:00",
    updated_at: "2025-01-20T16:45:00+08:00",
    evidence_files: [
      {
        id: "ev_001",
        file_name: "banking_screenshot.png",
        file_type: "image/png",
        file_size: 2048576,
        uploaded_at: "2025-01-20T09:20:00+08:00"
      },
      {
        id: "ev_002",
        file_name: "transaction_receipt.pdf",
        file_type: "application/pdf",
        file_size: 1024000,
        uploaded_at: "2025-01-20T09:22:00+08:00"
      },
      {
        id: "ev_003",
        file_name: "email_notification.png",
        file_type: "image/png",
        file_size: 856432,
        uploaded_at: "2025-01-20T09:25:00+08:00"
      }
    ]
  },
  {
    id: "CYB-2025-002",
    title: "Social Media Harassment",
    description: "Continuous harassment and threats received through social media platforms over the past month",
    priority: "medium",
    status: "Pending",
    officer: "Diana Lopez",
    unit: "Cyber Crime Against Women and Children",
    date: "2025-01-19",
    riskScore: 65,
    evidence: 5,
    crime_type: "Online Harassment",
    complainant: "Maria Santos",
    estimated_loss: 0,
    // Database schema fields
    user_id: "user_987654321",
    full_name: "Maria Santos",
    email: "maria.santos@email.com",
    phone_number: "+63 916 987 6543",
    incident_date_time: "2025-01-18T20:15:00+08:00",
    incident_location: "Online - Social Media Platforms",
    complaint_number: "CYB-2025-002",
    assigned_officer: "Diana Lopez",
    assigned_officer_id: "officer_004",
    assigned_unit: "Cyber Crime Against Women and Children",
    unit_id: "unit_003",
    // Dynamic fields (category-specific)
    platform_website: "Facebook, Instagram, Twitter",
    account_reference: "@mariasantos123, harassment_thread_001",
    // AI Enhancement fields
    ai_priority: "medium",
    ai_risk_score: 68,
    ai_confidence_score: 85,
    last_ai_assessment: "2025-01-19T08:45:00+08:00",
    remarks: "Case assigned to Cyber Crime Against Women and Children unit",
    created_at: "2025-01-19T08:30:00+08:00",
    updated_at: "2025-01-19T08:30:00+08:00",
    evidence_files: [
      {
        id: "ev_004",
        file_name: "facebook_threats.png",
        file_type: "image/png",
        file_size: 1234567,
        uploaded_at: "2025-01-19T08:35:00+08:00"
      },
      {
        id: "ev_005",
        file_name: "instagram_messages.png",
        file_type: "image/png",
        file_size: 987654,
        uploaded_at: "2025-01-19T08:37:00+08:00"
      },
      {
        id: "ev_006",
        file_name: "twitter_screenshots.png",
        file_type: "image/png",
        file_size: 1567890,
        uploaded_at: "2025-01-19T08:40:00+08:00"
      },
      {
        id: "ev_007",
        file_name: "messenger_conversation.pdf",
        file_type: "application/pdf",
        file_size: 2100000,
        uploaded_at: "2025-01-19T08:42:00+08:00"
      },
      {
        id: "ev_008",
        file_name: "profile_screenshots.png",
        file_type: "image/png",
        file_size: 789456,
        uploaded_at: "2025-01-19T08:45:00+08:00"
      }
    ]
  },
  {
    id: "CYB-2025-003",
    title: "Phishing Email Campaign",
    description: "Large-scale phishing campaign targeting bank customers with fake login pages",
    priority: "high",
    status: "Requires More Info",
    officer: "Carlos Mendoza",
    unit: "Cyber Crime Investigation Cell",
    date: "2025-01-18",
    riskScore: 92,
    evidence: 2,
    crime_type: "Phishing",
    complainant: "BPI Bank",
    estimated_loss: 250000,
    // Database schema fields
    user_id: "user_bpi_security",
    full_name: "BPI Security Team",
    email: "security@bpi.com.ph",
    phone_number: "+63 2 8840 4000",
    incident_date_time: "2025-01-17T10:00:00+08:00",
    incident_location: "Online - Email and Website",
    complaint_number: "CYB-2025-003",
    assigned_officer: "Carlos Mendoza",
    assigned_officer_id: "officer_003",
    assigned_unit: "Cyber Crime Investigation Cell",
    unit_id: "unit_001",
    // Dynamic fields (category-specific)
    platform_website: "fake-bpi-login.com",
    account_reference: "PHISH-CAM-001, affected_customers_batch_17",
    // AI Enhancement fields
    ai_priority: "high",
    ai_risk_score: 94,
    ai_confidence_score: 96,
    last_ai_assessment: "2025-01-18T14:35:00+08:00",
    remarks: "Requires additional server logs and affected customer list",
    created_at: "2025-01-18T14:20:00+08:00",
    updated_at: "2025-01-18T18:30:00+08:00",
    evidence_files: [
      {
        id: "ev_009",
        file_name: "phishing_email_sample.eml",
        file_type: "message/rfc822",
        file_size: 45632,
        uploaded_at: "2025-01-18T14:25:00+08:00"
      },
      {
        id: "ev_010",
        file_name: "fake_website_screenshot.png",
        file_type: "image/png",
        file_size: 3456789,
        uploaded_at: "2025-01-18T14:28:00+08:00"
      }
    ]
  },
  {
    id: "CYB-2025-004",
    title: "Identity Theft",
    description: "Personal information stolen and used to open fraudulent credit accounts",
    priority: "medium",
    status: "Under Investigation",
    officer: "Carlos Mendoza",
    unit: "Cyber Security Division",
    date: "2025-01-17",
    riskScore: 73,
    evidence: 4,
    crime_type: "Identity Theft",
    complainant: "Ana Reyes",
    estimated_loss: 75000,
    // Database schema fields
    assigned_officer_id: "officer_005",
    assigned_unit: "Cyber Security Division",
    unit_id: "unit_003",
    platform_website: "Various online services",
    account_reference: "SSS-123456789, PHILHEALTH-987654",
    ai_priority: "medium",
    ai_risk_score: 76,
    ai_confidence_score: 88,
    last_ai_assessment: "2025-01-17T14:20:00+08:00",
  },
  {
    id: "CYB-2025-005",
    title: "Ransomware Attack",
    description: "Company systems encrypted by ransomware with demand for ₱500,000 payment",
    priority: "high",
    status: "Resolved",
    officer: "Roberto Cruz",
    unit: "Cyber Crime Technical Unit",
    date: "2025-01-16",
    riskScore: 95,
    evidence: 7,
    crime_type: "Ransomware",
    complainant: "TechCorp Philippines",
    estimated_loss: 500000,
    // Database schema fields
    assigned_officer_id: "officer_006",
    assigned_unit: "Cyber Crime Technical Unit",
    unit_id: "unit_004",
    platform_website: "Corporate Network",
    account_reference: "RANSOM-DEMAND-XYZ789, SERVER-CLUSTER-01",
    ai_priority: "high",
    ai_risk_score: 98,
    ai_confidence_score: 99,
    last_ai_assessment: "2025-01-16T15:30:00+08:00",
  },
  {
    id: "CYB-2025-006",
    title: "Credit Card Fraud",
    description: "Unauthorized credit card transactions detected in multiple online purchases",
    priority: "medium",
    status: "Under Investigation",
    officer: "John Rodriguez",
    unit: "Economic Offenses Wing",
    date: "2025-01-15",
    riskScore: 68,
    evidence: 3,
    crime_type: "Credit Card Fraud",
    complainant: "Pedro Garcia",
    estimated_loss: 25000,
    // Database schema fields
    assigned_officer_id: "officer_002",
    assigned_unit: "Economic Offenses Wing",
    unit_id: "unit_002",
    platform_website: "Shopee, Lazada",
    account_reference: "CC-1234-****-5678, TXN-REF-998877",
    ai_priority: "medium",
    ai_risk_score: 71,
    ai_confidence_score: 84,
    last_ai_assessment: "2025-01-15T16:45:00+08:00",
  },
  {
    id: "CYB-2025-007",
    title: "Cyberbullying Case",
    description: "Student experiencing cyberbullying through various social media platforms and messaging apps",
    priority: "low",
    status: "Pending",
    officer: "Diana Lopez",
    unit: "Cyber Crime Against Women and Children",
    date: "2025-01-14",
    riskScore: 45,
    evidence: 2,
    crime_type: "Cyberbullying",
    complainant: "Rosa Mendoza",
    estimated_loss: 0,
    // Database schema fields
    assigned_officer_id: "officer_004",
    assigned_unit: "Cyber Crime Against Women and Children",
    unit_id: "unit_003",
    platform_website: "TikTok, Discord",
    account_reference: "@rosam_student, bullying_group_chat_445",
    ai_priority: "low",
    ai_risk_score: 48,
    ai_confidence_score: 78,
    last_ai_assessment: "2025-01-14T11:20:00+08:00",
  },
  {
    id: "CYB-2025-008",
    title: "Data Breach Investigation",
    description: "Personal data of 10,000 customers leaked from company database",
    priority: "high",
    status: "Under Investigation",
    officer: "Carlos Mendoza",
    unit: "Cyber Security Division",
    date: "2025-01-13",
    riskScore: 88,
    evidence: 6,
    crime_type: "Data Breach",
    complainant: "DataSecure Inc",
    estimated_loss: 100000,
    // Database schema fields
    assigned_officer_id: "officer_005",
    assigned_unit: "Cyber Security Division",
    unit_id: "unit_003",
    platform_website: "Company Database Server",
    account_reference: "DB-SERVER-001, BREACH-LOG-13012025",
    ai_priority: "high",
    ai_risk_score: 91,
    ai_confidence_score: 94,
    last_ai_assessment: "2025-01-13T16:30:00+08:00",
  },
  {
    id: "CYB-2025-009",
    title: "Sextortion Case",
    description: "Victim being blackmailed with intimate images shared through social media",
    priority: "high",
    status: "Requires More Info",
    officer: "Diana Lopez",
    unit: "Cyber Crime Against Women and Children",
    date: "2025-01-12",
    riskScore: 90,
    evidence: 3,
    crime_type: "Sextortion",
    complainant: "Confidential",
    estimated_loss: 0,
    // Database schema fields
    assigned_officer_id: "officer_004",
    assigned_unit: "Cyber Crime Against Women and Children",
    unit_id: "unit_003",
    platform_website: "Instagram, Telegram",
    account_reference: "CONFIDENTIAL_CASE_009",
    ai_priority: "high",
    ai_risk_score: 93,
    ai_confidence_score: 91,
    last_ai_assessment: "2025-01-12T10:45:00+08:00",
  },
  {
    id: "CYB-2025-010",
    title: "Government System Hacking",
    description: "Unauthorized access attempt detected on local government database system",
    priority: "high",
    status: "Under Investigation",
    officer: "Sofia Reyes",
    unit: "National Security Cyber Division",
    date: "2025-01-11",
    riskScore: 95,
    evidence: 4,
    crime_type: "Government System Hacking",
    complainant: "City Government of Manila",
    estimated_loss: 0,
    // Database schema fields
    assigned_officer_id: "officer_007",
    assigned_unit: "National Security Cyber Division",
    unit_id: "unit_008",
    platform_website: "manila.gov.ph",
    account_reference: "GOV-SYS-BREACH-001, FIREWALL-LOG-110125",
    ai_priority: "high",
    ai_risk_score: 97,
    ai_confidence_score: 98,
    last_ai_assessment: "2025-01-11T13:15:00+08:00",
  },
]

