export const mockCases = [
  {
    id: "CYB-2025-001",
    title: "Online Banking Fraud",
    priority: "high",
    status: "Under Investigation",
    officer: "Officer Martinez",
    unit: "Economic Offenses Wing",
    date: "2025-01-20",
    riskScore: 85,
    evidence: 3,
  },
  {
    id: "CYB-2025-002",
    title: "Social Media Harassment",
    priority: "medium",
    status: "Pending",
    officer: "Officer Chen",
    unit: "Cyber Crime Against Women and Children",
    date: "2025-01-19",
    riskScore: 65,
    evidence: 5,
  },
  {
    id: "CYB-2025-003",
    title: "Phishing Email Campaign",
    priority: "high",
    status: "Requires More Info",
    officer: "Officer Johnson",
    unit: "Cyber Crime Investigation Cell",
    date: "2025-01-18",
    riskScore: 92,
    evidence: 2,
  },
  {
    id: "CYB-2025-004",
    title: "Identity Theft",
    priority: "medium",
    status: "Under Investigation",
    officer: "Officer Rodriguez",
    unit: "Cyber Security Division",
    date: "2025-01-17",
    riskScore: 73,
    evidence: 4,
  },
  {
    id: "CYB-2025-005",
    title: "Ransomware Attack",
    priority: "high",
    status: "Resolved",
    officer: "Officer Kim",
    unit: "Cyber Crime Technical Unit",
    date: "2025-01-16",
    riskScore: 95,
    evidence: 7,
  },
  {
    id: "CYB-2025-006",
    title: "Credit Card Fraud",
    priority: "medium",
    status: "Under Investigation",
    officer: "Officer Smith",
    unit: "Economic Offenses Wing",
    date: "2025-01-15",
    riskScore: 68,
    evidence: 3,
  },
  {
    id: "CYB-2025-007",
    title: "Cyberbullying Case",
    priority: "low",
    status: "Pending",
    officer: "Officer Martinez",
    unit: "Cyber Crime Against Women and Children",
    date: "2025-01-14",
    riskScore: 45,
    evidence: 2,
  },
  {
    id: "CYB-2025-008",
    title: "Data Breach Investigation",
    priority: "high",
    status: "Under Investigation",
    officer: "Officer Smith",
    unit: "Cyber Security Division",
    date: "2025-01-13",
    riskScore: 88,
    evidence: 6,
  },
]

export const mockOfficers = [
  { id: 1, name: "Officer Martinez", unit: "Economic Offenses Wing", cases: 12, resolved: 8, badge: "PNP-001" },
  {
    id: 2,
    name: "Officer Chen",
    unit: "Cyber Crime Against Women and Children",
    cases: 15,
    resolved: 11,
    badge: "PNP-002",
  },
  { id: 3, name: "Officer Johnson", unit: "Cyber Crime Investigation Cell", cases: 9, resolved: 7, badge: "PNP-003" },
  { id: 4, name: "Officer Rodriguez", unit: "Cyber Security Division", cases: 18, resolved: 14, badge: "PNP-004" },
  { id: 5, name: "Officer Kim", unit: "Cyber Crime Technical Unit", cases: 11, resolved: 9, badge: "PNP-005" },
  { id: 6, name: "Officer Smith", unit: "Economic Offenses Wing", cases: 14, resolved: 10, badge: "PNP-006" },
]
